services:
  nginx:
   image: nginx
   build:
    context: .
    dockerfile: Dockerfilenginx
   ports:
      - 80:80
   volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
  php:
   image: php:7.2-fpm
   build: .
